---
title: "DRC VC site selection"
author: "Paul Bessell"
date: "2024-04-01"
output: html_document
params:
  RiverBuffer: 5000
  RiverDischarge: 15
  MinimumCases: 5
---

```{r setup, include=FALSE, warning=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
setwd("../")
riverBuff <- params$RiverBuffer
villageBuff <- 1000
riverFlowCutoff <- params$RiverDischarge
caseWeight <- FALSE
startYear <- 2019
finalYear <- 2023
tYears <- finalYear - startYear +1
caseThreshold <- params$MinimumCases ### Add someting to look at case density

#source("scripts/River_Analysis_Script_20240401.R", encoding = "UTF-8")
source("https://github.com/paulbessell/DRC_Planning/blob/master/scripts/River_Analysis_Script_BDD_KOCC.R")

library(DT); library(leaflet); library(leaflet.providers)
```

## Introduction

How to pick Inaki's next holiday

```{r basic data table, echo = F}
cFilename <- paste0("RiversExport", Sys.Date())

ZSRiverDT <- ZSRiverOutput %>% 
                st_drop_geometry() %>% 
                mutate(across(where(is.numeric), ~round(., 3))) %>% 
                filter(CasesTotal > caseThreshold)
DT::datatable(ZSRiverDT, extensions = c('Scroller', 'Buttons', 'ColReorder'),
                            escape = FALSE,
                            options = list(deferRender = F,
                                           colReorder = TRUE,
                            scrollY = 300, 
                            scrollX = TRUE,
                            scroller = TRUE, pageLength = 4,
                            dom = 'Blfrtip',
                            buttons = list('copy',
                                           list(extend = 'csv', filename = cFilename),
                                           list(extend = 'excel', filename = cFilename),
                                           list(extend = 'pdf', filename = cFilename), 'print')),
                            selection = "none")

```


### <font size = "+2"> <b> Carte des fleuves </font size></b>
```{r Carte des fleuves, echo = F, out.width='100%'}
riversMapping <- ZSRiverOutput %>%
  filter(CasesTotal >= caseThreshold | (Start != 0))
riversMappingAll <- ZSRiverOutput %>%
  filter(CasesTotal < caseThreshold & (Start == 0))

riversMapping$lab <- paste0("<b>", "ZS = ", riversMapping$plZSAdj,
                            "<br/>", "Province = ", riversMapping$fProvince, 
                               "</b></b><br/>", "Intervention start = ", ifelse(riversMapping$Start==0, "", riversMapping$Start),
                            "</b><br/>", "Discharge (cm) = ", round(riversMapping$Discharge,1),    
                            "</b><br/>", "Total cases = ", round(riversMapping$CasesTotal,1),  
                               "</b><br/>", "Total weighted cases = ", round(riversMapping$WeightTotal,1),
                               "</b><br/>", "Cases / Km = ", round(riversMapping$casesKm,3),
                               "</b><br/>", "Weighted cases / Km = ", round(riversMapping$WeightKm,3),
                               "</b><br/>", "Length = ", round(riversMapping$RiverLength,1))

riversMappingAll$lab <- paste0("<b>", "ZS = ", riversMappingAll$plZSAdj,
                            "<br/>", "Province = ", riversMappingAll$fProvince, 
                            "</b></b><br/>", "Discharge (cm) = ", round(riversMappingAll$Discharge,1),    
                            "</b><br/>", "Total cases = ", round(riversMappingAll$CasesTotal,1),  
                               "</b><br/>", "Total weighted cases = ", round(riversMappingAll$WeightTotal,1),
                               "</b><br/>", "Cases / Km = ", round(riversMappingAll$casesKm,3),
                               "</b><br/>", "Weighted cases / Km = ", round(riversMappingAll$WeightKm,3),
                               "</b><br/>", "Length = ", round(riversMappingAll$RiverLength,1))

riversMappingNew <- riversMapping %>%
  filter(Start == 0)
  
riversMappingCurrent <- riversMapping %>%
  filter(Start !=0)

zsBDD <- zs %>%
  filter(PROVINCE %in% unique(rivers$fProvince))
zsBDD$lab <- paste0("<b>", "ZS = ", zsBDD$ZS,
                   "<br/>", "Province = ", zsBDD$PROVINCE, "</b>")

bounds <- riversMappingNew %>% 
  st_bbox() %>% 
  as.character()

  leaflet(riversMappingNew) %>%
    addTiles(group = "Streets") %>%
        addPolygons(data = zsBDD,
                fillColor = "white",
                fillOpacity = 0,
                color = "black",
                opacity = 0.5,
                weight = 1,
                highlightOptions = highlightOptions(stroke = 4, weight = 3, opacity = 1),
                popup = ~lapply(lab, htmltools::HTML)) %>%
        addPolygons(data = provinces,
                fill = NA,
                color = "black",
                opacity = 1.,
                weight = 2) %>%
    addPolylines(data = riversMappingAll,
                 popup = ~lapply(paste0("<b>", "Non-candidate", "<br/>",lab), htmltools::HTML),
                 opacity = 1,
                 weight = 1,
                 color = "#214C9F",
                 highlightOptions = highlightOptions(stroke = 4, weight = 6, opacity = 1),
                 group = "Non-Candidate") %>%
    addPolylines(popup = ~lapply(paste0("<b>", "Candidate site", "<br/>",lab), htmltools::HTML),
                 opacity = 1,
                 weight = 3,
                 color = "#BF180A",
                 highlightOptions = highlightOptions(stroke = 4, weight = 6, opacity = 1),
                 group = "New Interventions") %>%
    addPolylines(data = riversMappingCurrent,
                 popup = ~lapply(paste0("<b>", "Current site", "<br/>",lab), htmltools::HTML),
                 opacity = 1,
                 weight = 3,
                 color = "#214C9F",
                 highlightOptions = highlightOptions(stroke = 4, weight = 6, opacity = 1),
                 group = "Current Interventions") %>%
  fitBounds(bounds[1], bounds[2], bounds[3], bounds[4]) %>%
    addLayersControl(
      overlayGroups = c("New Interventions", "Current Interventions", "Non-Candidate"),
      options = layersControlOptions(collapsed = FALSE)
    ) %>%
    hideGroup("Non-Candidate")

```
